### ISSUE TITLE
errno

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#4]
I have an issue with getting the errno variable from libc because it can change in the midst of the native code calls. Is there any way you can possibly help me with this?

http://man7.org/linux/man-pages/man3/errno.3.html

**Comment by mezoni** [comment]
This code should work.

```dart
import "package:binary_interop/binary_interop.dart";

DynamicLibrary _dl;

BinaryTypes _bt;

BinaryData _errno;

int get errno {
  if (_errno == null) {
    _errno = _bt["int"].extern(_dl.symbol("errno"));
  }

  return _errno.value;
}
```

**Comment by kaendfinger** [comment]
Ahh, forgot about this pattern, thanks!

**Comment by mkustermann** [comment]
Just a side note: The errno variable may -- according to the manpage -- be a macro, in which case there might be no symbol in the library for it:

       errno  is  defined  by  the ISO C standard to be a modifiable lvalue of
       type int, and must not be explicitly declared; errno may  be  a  macro.
       errno  is  thread-local;  setting  it in one thread does not affect its
       value in any other thread.

Also: You have the assumptions that dart code cannot be moved from one native thread to another while dart code is running (since `errno` is thread-local, you **must** fetch it on the same native thread on which the syscall was made) and that there were no intermediate syscalls which could modify `errno` (e.g. the DartVM can make a runtime call to compile the `int get errno` getter, which might result in a `mmap` call, which can override `errno`).

But I'm not really familiar with the `package:binary_interop`, so maybe I misunderstand something.

**Comment by mezoni** [comment]
>> But I'm not really familiar with the package:binary_interop, so maybe I misunderstand something.

It is just a wrapper to "libffi".
https://sourceware.org/libffi

I don't think that original "libffi" intended to solve this problems.
The "binary interop" itself (not a "libffi") has its own data per each isolate because it written in Dart (and it are an isolate-safe). 

Also "libffi" does not allocates its own data critical with multi-threading.
The "binary interop" independently allocates the data and ask it to prepare the "cif" (calling interface).
The "binary interop" should free "cif" if it not required more.

I think that an "isolate" in Dart VM based on the "thread".
And if a some syscalls are "thread-safe" then you may use them in Dart VM.

About "errno".
Some features can be:
- Compiler dependent
- System dependent

If some feature implemented thorugh the "macro" in header file then I don't know how to help you.

Eg.

```
#define errno __kernel_syscal_errno__
#define __kernel_syscal_errno__ __kernel_syscal_errno
extern int __kernel_syscal_errno;
```

P.S.

Maybe I don't undestand you correctly

**Comment by mezoni** [comment]
1) The <errno.h> header file defines the integer variable errno.

So, "errno" is a variable with identifier "errno".
If it exported (as a variable) it should have a storage.

2) errno is defined by the ISO C standard to be a modifiable lvalue of  type int.

The "lvalue" means left hand side.

Eg.

```c
#define rvalue 0
int lvalue = rvalue;
rvalue = 1; // Error
```

Other questions?

**Comment by mezoni** [comment]
>> and must not be explicitly declared; errno may  be  a  macro.

I understand your fears.
At least, in Linux it available (`libc.so.6`)

```dart
import "package:binary_interop/binary_interop.dart";

void main() {
  var lib = DynamicLibrary.load("libc.so.6");
  print(lib);
  print(lib.symbol("errno"));
}
```

```
libc.so.6
-1239680276
```

**Comment by mezoni** [comment]
Sorry, for rude.
I translate with a Google Translator.
Translation sometimes terrible.

**Comment by mezoni** [comment]
@mkustermann 

>> (e.g. the DartVM can make a runtime call to compile the int get errno getter, which might result in a mmap call, which can override errno).

Not a problem.
The "errno" referenced by the virtual address.
More precisely it is a result of call of the `dlsym("errno")`

```
void *dlsym(void *handle, const char *name);
```

Even if the Dart VM move Dart `BinaryData errno` it cannot move `extern "C" { int errno; }`.
The `BinaryData errno` contains only address and read/write value each time from the memory (`extern int errno`).
It does not stores any data except the memory address.

binary_types/lib/src/data.dart
```dart
dynamic get value {
  return type._getValue(base, offset);
}
```

binary_types/lib/src/integers.dart
```dart
int _getValue(int base, int offset) {
  return new _PhysicalData(base, 0).getInt32(offset);
}
```

>> But I'm not really familiar with the package:binary_interop, so maybe I misunderstand something.

This related to `binary_types` but not the `binary_interop`.

**Comment by mezoni** [comment]
@mkustermann 

>> Also: You have the assumptions that dart code cannot be moved from one native thread to another while dart code is running (since errno is thread-local, you must fetch it on the same native thread on which the syscall was made) and that there were no intermediate syscalls which could modify errno

>> You have the assumptions that dart code cannot be moved from one native thread to another while dart code is running 

Not a code cannot be moved.
Code can be shared between threads.
Context of one isolate cannot be moved into the another isolate (eg. instruction pointer, stack pointer, other system hanldes).

>> and that there were no intermediate syscalls which could modify errno

Impossible perform an intermediate calls inside one isolate. Until the call does not return value a whole isolate will be blocked.
This is because syscall are synchrous call. All synchrous calls in Dart are blocked.
